version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiment_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app/src
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiment_worker
    command: celery -A core.infrastructure.adapters.input.celery_worker.worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - PYTHONPATH=/app/src
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
